//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Final_Desarrollo_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detalles_Compras_Farmacia
    {
        public int id_detalle_compra { get; set; }
        public int ID_Compra { get; set; }
        public int ID_Medicamento { get; set; }
        public int Cantidad { get; set; }
        public decimal Subtotal { get; set; }
    
        public virtual Compras_Farmacia Compras_Farmacia { get; set; }
        public virtual Medicamentos Medicamentos { get; set; }
    }
}
