//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Final_Desarrollo_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detalles_Compras_Farmacia
    {
        public int id_detalle_compra { get; set; }
        public int ID_Compra { get; set; }
        public int ID_Medicamento { get; set; }
        public int Cantidad { get; set; }
        public decimal Subtotal { get; set; }
    
        public virtual Compras_Farmacia Compras_Farmacia { get; set; }
        public virtual Medicamentos Medicamentos { get; set; }
    }
}
