//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Final_Desarrollo_Web.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FarmaUEntities : DbContext
    {
        public FarmaUEntities()
            : base("name=FarmaUEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Categorias> Categorias { get; set; }
        public virtual DbSet<Clientes> Clientes { get; set; }
        public virtual DbSet<Compras_Farmacia> Compras_Farmacia { get; set; }
        public virtual DbSet<Detalles_Compras_Farmacia> Detalles_Compras_Farmacia { get; set; }
        public virtual DbSet<Detalles_Factura> Detalles_Factura { get; set; }
        public virtual DbSet<Facturas> Facturas { get; set; }
        public virtual DbSet<Inventario> Inventario { get; set; }
        public virtual DbSet<Laboratorios> Laboratorios { get; set; }
        public virtual DbSet<Lotes> Lotes { get; set; }
        public virtual DbSet<Medicamentos> Medicamentos { get; set; }
        public virtual DbSet<Medicos> Medicos { get; set; }
        public virtual DbSet<Movimientos_Inventario> Movimientos_Inventario { get; set; }
        public virtual DbSet<Personas> Personas { get; set; }
        public virtual DbSet<Proveedores> Proveedores { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
    }
}
