//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Final_Desarrollo_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Imagenes_Producto
    {
        public int ID_Imagen { get; set; }
        public int ID_Producto { get; set; }
        public string URL { get; set; }
        public string Descripcion { get; set; }
        public bool EsPrincipal { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public bool Estado { get; set; }
    
        public virtual Productos Productos { get; set; }
    }
}
