//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Final_Desarrollo_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medicamentos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Medicamentos()
        {
            this.Detalles_Compras_Farmacia = new HashSet<Detalles_Compras_Farmacia>();
            this.Detalles_Factura = new HashSet<Detalles_Factura>();
            this.Lotes = new HashSet<Lotes>();
            this.Movimientos_Inventario = new HashSet<Movimientos_Inventario>();
        }
    
        public int ID_Medicamento { get; set; }
        public int ID_Categoría { get; set; }
        public int ID_Laboratorio { get; set; }
        public string Nombre { get; set; }
        public string principio_activo { get; set; }
        public decimal precio_compra { get; set; }
        public decimal precio_venta { get; set; }
        public string estado { get; set; }
    
        public virtual Categorias Categorias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Detalles_Compras_Farmacia> Detalles_Compras_Farmacia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Detalles_Factura> Detalles_Factura { get; set; }
        public virtual Laboratorios Laboratorios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lotes> Lotes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Movimientos_Inventario> Movimientos_Inventario { get; set; }
    }
}
