//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Final_Desarrollo_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medicos
    {
        public int id_Medico { get; set; }
        public int ID_Persona { get; set; }
        public string Especialidad { get; set; }
        public string registro_medico { get; set; }
    
        public virtual Personas Personas { get; set; }
    }
}
