//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Final_Desarrollo_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movimientos_Inventario
    {
        public int ID_movimiento { get; set; }
        public int id_medicamento { get; set; }
        public int id_Lote { get; set; }
        public string tipo { get; set; }
        public int cantidad { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<int> id_Compra { get; set; }
        public Nullable<int> ID_Factura { get; set; }
    
        public virtual Compras_Farmacia Compras_Farmacia { get; set; }
        public virtual Facturas Facturas { get; set; }
        public virtual Lotes Lotes { get; set; }
        public virtual Medicamentos Medicamentos { get; set; }
    }
}
