//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Final_Desarrollo_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuarios()
        {
            this.Carrito = new HashSet<Carrito>();
        }
    
        public int ID_Usuario { get; set; }
        public int ID_Persona { get; set; }
        public int ID_Rol { get; set; }
        public string hash_clave { get; set; }
        public int estado { get; set; }
        public Nullable<System.DateTime> ultimo_login { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public string usuario { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Carrito> Carrito { get; set; }
        public virtual Personas Personas { get; set; }
        public virtual Roles Roles { get; set; }
    }
}
