//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Final_Desarrollo_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        public int ID_Usuario { get; set; }
        public int ID_Persona { get; set; }
        public int ID_Rol { get; set; }
        public string hash_clave { get; set; }
        public int estado { get; set; }
        public Nullable<System.DateTime> ultimo_login { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public string usuario { get; set; }
    
        public virtual Personas Personas { get; set; }
        public virtual Roles Roles { get; set; }
    }
}
